# Generated by Django 3.2.6 on 2021-09-07 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=20)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('for_who', models.CharField(choices=[('staff', 'staff'), ('manager', 'manager'), ('texnolog', 'texnolog')], default='staff', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('un_calculate', 'un_calculate'), ('calculated', 'calculated')], default='un_calculate', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('not_given', 'not_given'), ('given', 'given'), ('calculated', 'calculated')], default='not_given', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologicalSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('not_given', 'not_given'), ('given', 'given'), ('calculated', 'calculated')], default='not_given', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
