# Generated by Django 3.2.6 on 2021-09-07 09:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUnFitBiscuitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unfit_biscuit_id', models.PositiveIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('recyclable', 'recyclable'), ('unrecyclable', 'unrecyclable')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyingBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default="so'm", max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('credit_card', 'credit_card'), ('debt', 'debt')], default='cash', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('take_driver', 'take_driver'), ('delivered', 'delivered')], default='pending', max_length=50)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyingBiscuitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.PositiveIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default="so'm", max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('credit_card', 'credit_card'), ('debt', 'debt')], default='cash', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(blank=True, default="so'm", max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(blank=True, default="so'm", max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('unpaid', 'unpaid'), ('paid', 'paid')], default='unpaid', max_length=50, null=True)),
                ('for_price', models.CharField(choices=[('un_calculate', 'un_calculate'), ('calculated', 'calculated')], default='un_calculate', max_length=50)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnfitBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recyclable', 'recyclable'), ('unrecyclable', 'unrecyclable')], max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
        migrations.CreateModel(
            name='SaleBiscuitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceBiscuitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(blank=True, default="so'm", max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=200, null=True)),
                ('produce_biscuit_id', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
    ]
