# Generated by Django 3.2.6 on 2021-09-10 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_client', '0001_initial'),
        ('apps_biscuit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbiscuit',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnbiscuit',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
