# Generated by Django 3.2.6 on 2021-09-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_supplier', '0001_initial'),
        ('apps_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_supplier.supplier'),
        ),
        migrations.AddField(
            model_name='manufacturedproductpricelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.manufacturedproduct'),
        ),
        migrations.AddField(
            model_name='addproductlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.product'),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.product'),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_supplier.supplier'),
        ),
    ]
