# Generated by Django 3.2.6 on 2021-09-07 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='warehouseman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addmanufacturedproductlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.manufacturedproduct'),
        ),
        migrations.AddField(
            model_name='addmanufacturedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.manufacturedproduct'),
        ),
    ]
