# Generated by Django 3.2.6 on 2021-09-15 06:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0003_initial'),
        ('apps_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_box', models.CharField(help_text='karobka yoki salafan nomi', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('note', models.CharField(blank=True, help_text='Izoh', max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.product')),
            ],
        ),
    ]
