# Generated by Django 3.2.6 on 2021-09-08 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='clientorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('pending', 'pending'), ('completed', 'completed')], default='new', max_length=50, null=True),
        ),
    ]
