# Generated by Django 3.2.6 on 2021-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('parents_name', models.CharField(max_length=200)),
                ('parents_birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=14)),
                ('welcome_date', models.DateField()),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=14)),
                ('xr', models.CharField(max_length=100)),
                ('mfo', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
