# Generated by Django 3.2.6 on 2021-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_supplier', '0003_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
    ]
