# Generated by Django 3.2.6 on 2021-09-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_supplier', '0004_alter_employee_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
