# Generated by Django 3.2.6 on 2021-09-07 09:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuantityExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default="So'm", max_length=10)),
                ('status', models.CharField(choices=[('new', 'new'), ('completed', 'completed')], default='new', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_expense.expense')),
            ],
        ),
    ]
